### ISSUE TITLE
group 7 

### ISSUE THREAD

**Issue by chadxsmith** [ga-dc/wdidc5-project2#10]
when attempting to save user information, we're experiencing the following error: 

```
No route matches {:action=>"show", :controller=>"homeless_people"} missing required keys: [:city_id, :id]

```

the highlighted code's posted below:

```
    @user = User.new( user_params )
        if @user.save
            redirect_to city_homeless_person_path
        else
            render :new
        end

```

**Comment by adambray** [comment]
I helped them resolve this issue. Awaiting them to update with description of fix and close.

**Comment by adambray** [comment]
@chadxsmith @btf5048 please update this issue with a summary of what you did to fix it and then close it! (assuming you're solved this issue).
