### ISSUE TITLE
Group 9

### ISSUE THREAD

**Issue by dmjurg** [ga-dc/wdidc5-project2#11]
The user story we are stuck on is: Allow a user to log in and create a profile (and from there create stories)

Our models are as follows:
USER has_one PROFILE (one-to-one relationship, User also has_many STORIES through PROFILE)
PROFILE has_many STORIES (one-to-many relationship)

When we first created the rails app, we only had two models - Profile and Story.  We added User when we installed the Devise gem.  I am struggling to correctly create the associations between the models with this new addition.

I am currently getting the below error when i run the #rake db:seed command:

ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "profiles" violates foreign key constraint "fk_rails_561847c27c" on table "stories"
DETAIL:  Key (id)=(1) is still referenced from table "stories".
: DELETE FROM "profiles" WHERE "profiles"."id" = $1

I have gone through some of the ActiveRecord documentation regarding associations as well as nested attributes.  I also looked at some of the PostgreSQL documentation, but I am a little unclear as to what exactly this error means.

**Comment by jshawl** [comment]
What if you destroy and then recreate all the data:

```
Rake db:migrate:reset 
Rake db:seed
```
