### ISSUE TITLE
Creating new comment, can't access the post id for where the comment lives

### ISSUE THREAD

**Issue by ryankeiper** [ga-dc/wdidc5-project2#13]
We're trying to add comment CRUD functionality to our "results" model, so each result will have several comments that live on that page. But when trying to create a new comment, @result doesn't save the params[:id] we're trying to reference:

```
def create
    @result = Result.find( params[:id] )
    @comment = @result.comments.new( comment_params )
    if @comment.save
      redirect_to @result
    else
      render :new
    end
  end
```

We always get the error "Couldn't find Result with 'id'=".

Thoughts on why this isn't populating the id field or finding that result? We suspect it might have to do with us working on the comments controller trying to find this result, but we're not sure how to get around that.

**Comment by RobertAKARobin** [comment]
That means `params[:id]` is blank. Are you sure you're GETing and POSTing appropriately to the `create` route?

**Comment by ryankeiper** [comment]
We tracked down Eltahir and talked it out with him, it was because we didn't have our comments route nested within our results route, dang it. We redid it that way and changed all the paths and got it working. Hurrah!
