### ISSUE TITLE
SO close to getting this quiz to work

### ISSUE THREAD

**Issue by ryankeiper** [ga-dc/wdidc5-project2#17]
My quiz is a LOT closer to working. The radio buttons work, each question displays on a new page, the next button at the bottom saves the answer to the database, and the logic in the controller tallies up the answers into a result. BUT. It isn't storing A, B, C, D or E in each database entry. It's leaving that blank, and the corresponding question_id is always being stored as zero for some reason. I just can't quite find why it's not storing those values, if I could it would work! I suspect it's in my form somewhere, here's the code for that:

```
<h3><%= @question.id %>. <%= @question.wording %></h3>

<% @user_response = @question.user_responses.new %>

<%= form_for [@question, @user_response] do |f| %>
    <% @question.question_answers.each do |answer| %>
    <p><%= answer.value %>
      <p><%= f.radio_button :question_id, answer.value %>
      <%= f.label "answer_for_question_#{@question.id}", answer.wording %></p>
    <% end %>
    <%= f.submit "Next" %>
<% end %>
```

Any thoughts on what I'm missing or where else to look to find why it isn't pulling the value parameter from the selected answer and storing it as the response parameter for each user_response?

**Comment by RobertAKARobin** [comment]
Sorry for the delay, Ryan: a couple of this looked at this, thought it was fine, and so hoped the next person would have the answer! I'm afraid the answer must be somewhere else in your code. Did you modify the `create` controller?
