### ISSUE TITLE
group 8

### ISSUE THREAD

**Issue by presto2116** [ga-dc/wdidc5-project2#7]
working with radio buttons, and they will not save to a boolean. Also have several other problems that need help talking through

**Comment by RobertAKARobin** [comment]
Radio buttons don't save to a boolean; checkboxes do. Radio buttons save to a string value.

Submit code with your issue!

**Comment by presto2116** [comment]
We just submitted a quick issue since we were in line for the Genius Bar. Got an answer. But the answer made us have to rewrite the entire code.

**Comment by RobertAKARobin** [comment]
Been there.
