### ISSUE TITLE
Group 3 

### ISSUE THREAD

**Issue by philw214** [ga-dc/wdidc5-project2#8]
![screen shot 2015-04-21 at 4 05 25 pm](https://cloud.githubusercontent.com/assets/11447889/7261539/81cbf6a2-e840-11e4-9196-a7bc29cea969.png)

**Comment by andrewsunglaekim** [comment]
what's causing this error?

**Comment by philw214** [comment]
Application Controller

**Comment by philw214** [comment]
after running rails s, I can't view the profiles index page via localhost
