### ISSUE TITLE
Having trouble with a pull request

### ISSUE THREAD

**Issue by amaseda** [ga-dc/wdidc5-project2#9]
GitHub says it can't automatically merge a pull request. The conflict seems to be due to small changes in indentation to some files but we can't resolve the conflict.

**Comment by RobertAKARobin** [comment]
Can you link to the pull request?

**Comment by jshawl** [comment]
you could also try manually merging:

```
git remote add their-name git@github.com:their-user-name/their-fork-name.git
git pull their-name their-branch-name
```

**Comment by amaseda** [comment]
@RobertAKARobin Here's the pull request: https://github.com/amaseda/learn_tech/pull/7#event-286586498

**Comment by amaseda** [comment]
@RobertAKARobin @jshawl We seemed to have fixed it. Not entirely sure how. But thanks for getting back to me!
